[mypy]
ignore_missing_imports = True
disable_error_code = import-untyped, assignment, misc, operator, arg-type, annotation-unchecked
explicit_package_bases = False
exclude = (?x)(
    ^venv/
    | ^\.venv/
  )
